### ISSUE TITLE
AppsFlyer Unified Deep Linking does not work for terminated app when integrating Segment-AppsFlyer in device-mode

### ISSUE THREAD

**Issue by tankietkt** [AppsFlyerSDK/appsflyer-segment-android-plugin#45] opened 2021-06-09 08:41 UTC
# Report

## Plugin Version

6.3.0

## On what Platform are you having the issue?

Android - React Native

## What did you do?

Integrate AppsFlyer destination with Segment to track events via device-mode
```
Analytics.Builder builder = new Analytics.Builder(this , BuildConfig.SEGMENT_WRITE_KEY);
builder.use(AppsflyerIntegration.FACTORY);
```

## What did you expect to happen?

AppsFlyer Unified Deep Linking still works for every case

## What happened instead?

AppsFlyer Unified Deep Linking does not work when user opens the app from cold start
`onDeepLink` at [#L169](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java#L169) is not triggered

Deep linking still works when user opens the app from background state

## Please provide any other relevant information.

If I comment out `builder.use(AppsflyerIntegration.FACTORY);`, deep linking will work properly

**Comment by af-margot** [comment] 2021-06-23 09:04
Hi @tankietkt, 

Sorry for the late reply. We are not able to reproduce the issue. 
Are you still having the issue? If yes, I would suggest opening a ticket to [support](support@appsflyer.com).

**Comment by af-margot** [comment] 2021-11-22 12:50
Hi @tankietkt, 
We are closing this ticket for now. Feel free to re-open it if you are still experiencing this issue.

**Closed by af-margot** 2021-11-22 12:50 UTC
